### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [RiaJ16/H-Tech_SIG#1]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by RiaJ16** [comment]
Changes done.
Thanks.

Jair

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pcav** [comment]
Files still in the repo.
