### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Jefersonnnn** [RiaJ16/H-Tech_SIG#2]
Hello,
I'm having a problem trying to install this add-on. the following message appears. "**Unable to load '_sigrdap_' plugin Due to an error while calling the method Class Factory().**"

"**ModuleNotFoundError: No module named '_objdict_'**"

Any idea what might be happening?
I created the HOME environment variable.

Thank you.

![erroqgis](https://user-images.githubusercontent.com/15790917/57137512-6f306a80-6d86-11e9-9cd2-4b0a00828d84.PNG)

**Comment by RiaJ16** [comment]
Sorry for the issue, I forgot to mention you have to install two dependencies in python to be able to run this plugin. I've updated [readme file](https://github.com/RiaJ16/H-Tech_SIG/blob/master/README.md) with instructions.
