### ISSUE TITLE
H-Tech Cloud Account

### ISSUE THREAD

**Issue by AugustoFeron** [RiaJ16/H-Tech_SIG#3]
I installed the app, but I can not use any function. Do I need to have the H-Tech Cloud account? Where do I create this account?

![image](https://user-images.githubusercontent.com/50378886/57324476-3f62c900-70de-11e9-89a9-4c7d3af165dc.png)

**Comment by RiaJ16** [comment]
Yes, you need an account, but currently you need to be a client of H-Tech so we can provide one for you. I'm working on making this open for everyone.

**Comment by AugustoFeron** [comment]
Ok, got it.
Thank you!
